// Mock data shaped like the dashboard JSON the live UI consumes.
// Real source: data/dashboard/weekly_operational_report_<date>.json
window.DashboardData = {
  report: {
    kind: "weekly_operational_report",
    period_label: "02 – 08 апреля 2026",
    mode: "reused",
    source: "documents/requests",
    schema_version: "v3",
    available_reports: [
      "weekly_operational_report_2026-04-08",
      "market_margin_fit_2026-04-09",
      "dynamic_pricing_2026-04-09",
      "marketing_card_audit_2026-04-08",
      "cubejs_period_compare_2026-04-08",
    ],
  },
  flow_map: [
    { title: "Operational weekly", subtitle: "Запрос → CSV → operational bundle", state: "available", note: "succeeded · 14 сек" },
    { title: "Market margin fit",  subtitle: "Подниши и окна входа",            state: "runner",    note: "запускать через runner" },
    { title: "Buyer reviews",      subtitle: "Отзывы, вопросы, drafts",          state: "partial",   note: "часть слоя пока полу-ручной" },
  ],
  meta: [
    { label: "Период",         value: "02 – 08 апр 2026" },
    { label: "Режим получения", value: "reused" },
    { label: "Источник",       value: "weekly_operational_report" },
    { label: "Окно",           value: "7 дней" },
  ],
  kpis: [
    { label: "Выручка",         value: "1 248 600 ₽", delta:  12.4, info: "Без доставки, по сведённым SELLS_REPORT строкам." },
    { label: "Прибыль",         value: "284 100 ₽",   delta:   4.8 },
    { label: "Заказы",          value: "1 412",        delta:   6.0 },
    { label: "Средний чек",     value: "884 ₽",        delta:  -2.1 },
    { label: "Активные SKU",    value: "412",          delta:   0 },
    { label: "Риск out-of-stock", value: "38",         delta:   6, deltaUnit: "SKU", tone: "bad" },
  ],
  priorities: [
    { tone: "good", badge: "Дозакупка", value: "14 SKU", text: "Темп продаж пробивает остаток в окне 7 дней. Закупка по списку reorder_now." },
    { tone: "warn", badge: "Markdown",  value: "9 SKU",  text: "Стоковый запас выше нормативного 2× — пора снижать цену до движения." },
    { tone: "bad",  badge: "Protect",   value: "6 SKU",  text: "Победители без подтверждённого ABC класса A. Не давать им провалиться." },
  ],
  changes: [
    { tone: "good", title: "Сильнее по выручке",      text: "Выручка +12.4% к прошлой неделе — основной вклад дали группы Конструкторы и Гели для бровей." },
    { tone: "warn", title: "Семейства с шумом",        text: "Карточка с 6 вариантами: 4 не продавались — смотреть на семейство, а не на строку." },
    { tone: "bad",  title: "Затоваривание усиливается", text: "3 группы превысили нормативный сток 2× — без markdown будут давить экономику." },
  ],
  reorder_now: [
    { title: "Конструктор магнитный, 48 деталей", meta: "остаток 12 · 7-дн темп 4.2 · sku 098-A" },
    { title: "Гель-краска для бровей, тон 02",   meta: "остаток 6 · 7-дн темп 2.1 · sku 412-G" },
    { title: "Рюкзак школьный, серия Galaxy",     meta: "остаток 4 · 7-дн темп 1.6 · sku 217-R" },
    { title: "Подставка для книг, регулируемая",  meta: "остаток 8 · 7-дн темп 3.0 · sku 064-S" },
  ],
  markdown_candidates: [
    { title: "Набор фломастеров, 24 шт",    meta: "stale 96 дн · цена 489 ₽ · sku 311-F" },
    { title: "Сумка-холодильник, 12 л",     meta: "stale 81 день · цена 1 290 ₽ · sku 802-C" },
    { title: "Доска для мела A4",            meta: "stale 73 дня · цена 359 ₽ · sku 451-B" },
  ],
  protect_winners: [
    { title: "Конструктор магнитный, 48 деталей", meta: "ABC A · 7-дн темп 4.2 · профит 38%" },
    { title: "Гель-краска для бровей, тон 02",   meta: "ABC A · 7-дн темп 2.1 · профит 41%" },
    { title: "Рюкзак Galaxy, M",                 meta: "ABC B · 7-дн темп 1.6 · профит 32%" },
  ],
  current_winners: [
    { title: "Конструктор магнитный, 48 деталей", meta: "1 412 ₽ · 8 заказов · profit 38%" },
    { title: "Гель-краска для бровей, тон 02",   meta: "489 ₽ · 12 заказов · profit 41%" },
    { title: "Подставка для книг, регулируемая",  meta: "590 ₽ · 7 заказов · profit 34%" },
    { title: "Рюкзак Galaxy M",                  meta: "2 190 ₽ · 4 заказа · profit 32%" },
  ],
  profit_leaders: [
    { title: "Гель-краска для бровей, тон 02",   meta: "5 868 ₽ профит · profit 41%" },
    { title: "Конструктор магнитный, 48 деталей", meta: "4 290 ₽ профит · profit 38%" },
    { title: "Сумка тоут, плотная",              meta: "3 940 ₽ профит · profit 36%" },
  ],
  stock_risk: [
    { title: "Подставка для книг, регулируемая",  meta: "остаток 8 · темп 3.0 · 2.6 дн до 0" },
    { title: "Конструктор магнитный, 48 деталей", meta: "остаток 12 · темп 4.2 · 2.8 дн до 0" },
    { title: "Гель-краска для бровей, тон 02",   meta: "остаток 6 · темп 2.1 · 2.8 дн до 0" },
  ],
  stale_stock: [
    { title: "Набор фломастеров, 24 шт",    meta: "stale 96 дн · остаток 64 · 0 продаж в окне" },
    { title: "Сумка-холодильник, 12 л",     meta: "stale 81 день · остаток 18 · 0 продаж в окне" },
    { title: "Доска для мела A4",            meta: "stale 73 дня · остаток 30 · 0 продаж в окне" },
  ],
  compare: [
    { badge: "Trailing 365", value: "14.2 M ₽", subtitle: "Выручка без доставки", delta:  18, deltaLabel: "YoY" },
    { badge: "YTD vs PYTD",  value: "3.9 M ₽",  subtitle: "Прибыль с начала года", delta:   4, deltaLabel: "YoY" },
    { badge: "3Y compare",   value: "1 240",     subtitle: "Заказов в окне",        delta: -12, deltaLabel: "3Y" },
  ],
  status_bars: [
    { key: "winners",    value: 148 },
    { key: "stock risk", value: 68 },
    { key: "stale",      value: 36 },
    { key: "dead",       value: 16 },
  ],
  trend: [
    { month: "2025-11", value: 0.9 },
    { month: "2025-12", value: 1.3 },
    { month: "2026-01", value: 1.1 },
    { month: "2026-02", value: 1.6 },
    { month: "2026-03", value: 1.5 },
    { month: "2026-04", value: 1.9 },
  ],
  abc: { a: 18, b: 32, c: 50 },
  quick_wins_backlog: [
    { id: "reorder",   kind: "reorder",   count: 14, label: "Утвердить reorder_now",        action: "Открыть список", priority: 1 },
    { id: "markdown",  kind: "markdown",  count: 9,  label: "Согласовать markdown",          action: "Открыть список", priority: 2 },
    { id: "reviews",   kind: "reviews",   count: 2,  label: "Ответить покупателям",          action: "К отзывам",       priority: 3 },
    { id: "weekly",    kind: "run_job",   count: 1,  label: "Запустить weekly_operational",  action: "К runner",        priority: 4 },
    { id: "price_trap", kind: "price_trap", count: 6, label: "Подвинуть цены за пороги",      action: "Открыть список", priority: 5 },
    { id: "title_seo", kind: "title_seo", count: 3,  label: "Поправить слабые title",        action: "Открыть список", priority: 6 },
    { id: "watchlist", kind: "watchlist", count: 5,  label: "Проверить watchlist",            action: "Открыть список", priority: 7 },
    { id: "question",  kind: "questions", count: 1,  label: "Ответить на вопрос Игоря",      action: "К вопросу",        priority: 8 },
  ],
  watchlist: [
    { title: "Конструктор магнитный, 48 деталей", meta: "добавлен 02 апр · ABC A · темп 4.2", owner: "Я" },
    { title: "Сумка-холодильник, 12 л",            meta: "добавлен 28 мар · stale 81 дн",      owner: "Я" },
    { title: "Гель-краска для бровей, тон 02",     meta: "добавлен 06 апр · negative review",  owner: "Я" },
  ],
  manual_actions: [
    { title: "Пересмотреть закупку Galaxy серии",  meta: "до 12 апр · приоритет high",  owner: "Я",      status: "in_progress" },
    { title: "Сфотографировать конструктор крупно", meta: "до 14 апр · приоритет medium", owner: "Студия", status: "todo" },
    { title: "Обновить title для гель-краски",      meta: "сделано 08 апр",               owner: "Я",      status: "done" },
  ],
  action_center_status: [
    { label: "Открытых задач", value: "7" },
    { label: "Просрочено",     value: "1" },
    { label: "В watchlist",     value: "12" },
    { label: "Сохранённых view", value: "3" },
  ],
  queue_status: [
    { key: "todo",        value: 6 },
    { key: "in_progress", value: 4 },
    { key: "blocked",     value: 1 },
    { key: "done",        value: 14 },
  ],
  queue_owner: [
    { key: "Я",       value: 11 },
    { key: "Студия",  value: 3 },
    { key: "Логист",  value: 2 },
    { key: "Без",      value: 1 },
  ],
  saved_views: [
    { name: "Сегодня",         filters: "owner=я · status=todo,in_progress",   count: 9 },
    { name: "Просрочки",        filters: "due<today",                            count: 1 },
    { name: "Студия — фото",    filters: "owner=студия",                         count: 3 },
  ],
  entity_detail: {
    title: "Конструктор магнитный, 48 деталей",
    position_label: "ABC A · top-12 по выручке",
    cross_label: "также в watchlist",
    sku: "sku 098-A · ШК 4607123 · product_id 91823",
    note: "Карточка собрана из 3 вариантов; основной вес тянет вариант '48 деталей, синий'.",
    history: [
      { week: "W-9", value: 18 }, { week: "W-8", value: 22 },
      { week: "W-7", value: 19 }, { week: "W-6", value: 28 },
      { week: "W-5", value: 24 }, { week: "W-4", value: 31 },
      { week: "W-3", value: 26 }, { week: "W-2", value: 36 },
      { week: "W-1", value: 29 }, { week: "W-0", value: 34 },
    ],
    history_label: "Продано за неделю",
    log: [
      { when: "08 апр", text: "Добавлен в watchlist менеджером" },
      { when: "07 апр", text: "Темп продаж пробил остаток — попал в reorder_now" },
      { when: "02 апр", text: "Пересобран по новому ШК (4607123)" },
      { when: "28 мар", text: "Перешёл в ABC A по выручке (4 недели подряд)" },
    ],
  },
  reviews: [
    { kind: "review", rating: 5, title: "Конструктор магнитный, 48 деталей", meta: "Виктория Е. · 3 апреля", text: "Покупала ребёнку 7 лет. Магниты держат, детали без заусенцев, упаковка крепкая. Спасибо!", status: "sent" },
    { kind: "review", rating: 2, title: "Гель-краска для бровей, тон 02",   meta: "Анна Ч. · 6 апреля", text: "Цвет светлее, чем на фото. И флакон пришёл подтекающим — крышка не довинчена.", status: "draft" },
    { kind: "question", title: "Рюкзак Galaxy M", meta: "Игорь Т. · 7 апреля", text: "Подойдёт ли для ноутбука 15.6\"? И есть ли отделение под зонт?", status: "approved" },
  ],
};
